Documentation:
    Enabled: false
Metrics/LineLength:
  Enabled: true
  Severity: warning
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/MethodLength:
  Enabled: true
  Max: 20
Naming/UncommunicativeMethodParamName:
  MinNameLength: 2
Lint/UnusedMethodArgument:
  Enabled: false
